# Generated by Django 3.2.6 on 2021-09-02 01:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apps_pregunchaco', '0003_auto_20210828_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizusuario',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='max_puntaje',
            field=models.IntegerField(default=5, verbose_name='Maximo Puntaje'),
        ),
        migrations.AlterField(
            model_name='preguntasrespondidas',
            name='puntaje_obtenido',
            field=models.IntegerField(default=0, verbose_name='Puntaje Obtenido'),
        ),
        migrations.AlterField(
            model_name='quizusuario',
            name='puntaje_total',
            field=models.IntegerField(default=0, verbose_name='Puntaje Total'),
        ),
    ]
